apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecomm
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: michealken30/frontend-js:latest
          env:
            - name: VITE_REACT_APP_API_URL
              value: "http://www.michealken30.com.ng/"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ecomm
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      protocol: TCP
      env:
        - name: VITE_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: firebase-api-key
  type: ClusterIP
