apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecomm-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michealken30/e-comm-funiture.git
    targetRevision: app-of-app
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
